# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
# entryPoint = "https"

# https is the default
#[entryPoints.https]
#address = ":443"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "lair.localhost"
watch = true
exposedbydefault = false